from homeassistant.const import EntityCategory

ALERT_SENSORS = [
    # Maintenance alerts (these are normal maintenance operations)
    {
        "name_pattern": "insert tray",
        "type": "insert_tray",
        "display_name": "Alarm - Insert Tray",
        # "icon": "mdi:tray",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "fill water",
        "type": "fill_water",
        "display_name": "Alarm - Fill Water",
        # "icon": "mdi:water",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "empty grounds",
        "type": "empty_grounds",
        "display_name": "Alarm - Empty Grounds",
        # "icon": "mdi:delete",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "empty tray",
        "type": "empty_tray",
        "display_name": "Alarm - Empty Tray",
        # "icon": "mdi:tray-alert",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    # Service alerts (require cleaning or filter replacement)
    {
        "name_pattern": "cleaning alert",
        "type": "cleaning_alert",
        "display_name": "Alarm - Cleaning Needed",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "filter alert",
        "type": "filter_alert",
        "display_name": "Alarm - Filter Change Needed",
        # "icon": "mdi:air-filter",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    }, 
    {
        "name_pattern": "cappu rinse alert",
        "type": "cappu_rinse_alert",
        "display_name": "Alarm - Milk System Rinse Needed",
        # "icon": "mdi:cup-water",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "cappu clean alert",
        "type": "cappu_clean_alert",
        "display_name": "Alarm - Milk System Cleaning Needed",
        # "icon": "mdi:cup-water",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "Coffee Eye (cup detected)",
        "type": "Coffee_Eye_(cup_detected)",
        "display_name": "Info - Coffee Eye (cup detected)",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "Info - cappu clean alert",
        "type": "Info_-_cappu_clean_alert",
        "display_name": "Alarm - Info - cappu clean alert",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "Info - coffee clean alert",
        "type": "Info_-_coffee_clean_alert",
        "display_name": "Alarm - Info - coffee clean alert",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "Info - decalc alert",
        "type": "Info_-_decalc_alert",
        "display_name": "Alarm - Info - decalc alert",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "Info - filter used up alert",
        "type": "Info_-_filter_used_up_alert",
        "display_name": "Alarm - Info - filter used up alert",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "LockedKeys",
        "type": "LockedKeys",
        "display_name": "Info - LockedKeys",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "ML/OZ status",
        "type": "ML/OZ_status",
        "display_name": "Info - ML/OZ status",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "Open Tap",
        "type": "Open_Tap",
        "display_name": "Info - Open Tap",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "RemoteScreen",
        "type": "RemoteScreen",
        "display_name": "Info - Remote Screen",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "SwitchOff Delay active",
        "type": "SwitchOff_Delay_active",
        "display_name": "Info - SwitchOff Delay active",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "active RF filter",
        "type": "active_RF_filter",
        "display_name": "Info - Filter Installed",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "close front cover",
        "type": "close_front_cover",
        "display_name": "Alarm - Close Front Cover",
        # "icon": "mdi:arrow-down-drop-circle",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "close powder cover",
        "type": "close_powder_cover",
        "display_name": "Alarm - Close Powder Cover",
        # "icon": "mdi:cup",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "close tab",
        "type": "close_tab",
        "display_name": "Alarm - Close Tab",
        # "icon": "mdi:color-helper",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "coffee ready",
        "type": "coffee_ready",
        "display_name": "Info - Coffee Ready",
        # "icon": "mdi:coffee-to-go",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "coffee rinsing",
        "type": "coffee_rinsing",
        "display_name": "Info - Coffee Rinsing",
        # "icon": "mdi:cup-water",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "decalc alert",
        "type": "decalc_alert",
        "display_name": "Alarm - Decalc Needed",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "empty grounds RTC",
        "type": "empty_grounds_RTC",
        "display_name": "Alarm - Empty Grounds RTC",
        # "icon": "mdi:washing-machine",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "energy safe",
        "type": "energy_safe",
        "display_name": "Info - Energy Safe",
        # "icon": "mdi:power-settings",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "enjoy product",
        "type": "enjoy_product",
        "display_name": "Info - Enjoy Product",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "error milk (milk sensor)",
        "type": "error_milk_(milk_sensor)",
        "display_name": "Alarm - error milk (milk sensor)",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "error status",
        "type": "error_status",
        "display_name": "Alarm - error status",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "fill powder",
        "type": "fill_powder",
        "display_name": "Alarm - Fill Powder",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "fill system",
        "type": "fill_system",
        "display_name": "Alarm - Fill System",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "goodbye",
        "type": "goodbye",
        "display_name": "Info - Goodbye",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "heating up",
        "type": "heating_up",
        "display_name": "Info - Heating Up",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "insert coffee bin",
        "type": "insert_coffee_bin",
        "display_name": "Alarm - Insert Coffee Bin",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "left bean alert",
        "type": "left_bean_alert",
        "display_name": "Alarm - Left Bean Alert",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "milk alert",
        "type": "milk_alert",
        "display_name": "Alarm - Milk Alert",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "no beans",
        "type": "no_beans",
        "display_name": "Alarm - No Beans",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "no milk (milk sensor)",
        "type": "no_milk_(milk_sensor)",
        "display_name": "Alarm - no milk (milk sensor)",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "no signal (milk sensor)",
        "type": "no_signal_(milk_sensor)",
        "display_name": "Alarm - no signal (milk sensor)",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "not enough powder",
        "type": "not_enough_powder",
        "display_name": "Alarm - Not Enough Powder",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "outlet missing",
        "type": "outlet_missing",
        "display_name": "Alarm - Outlet Missing",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "periphery alert",
        "type": "periphery_alert",
        "display_name": "Alarm - Periphery Alert",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "please wait",
        "type": "please_wait",
        "display_name": "Info - Please Wait",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "powder product",
        "type": "powder_product",
        "display_name": "Info - Powder Product",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "press rinse",
        "type": "press_rinse",
        "display_name": "Alarm - Press Rinse",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "program-mode status",
        "type": "program-mode_status",
        "display_name": "Info - Program Mode Status",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "rear cover missing",
        "type": "rear_cover_missing",
        "display_name": "Alarm - Rear Cover Missing",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "remove water tank",
        "type": "remove_water_tank",
        "display_name": "Alarm - Remove Water Tank",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "right bean alert",
        "type": "right_bean_alert",
        "display_name": "Alarm - Right Bean Alert",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "steam ready",
        "type": "steam_ready",
        "display_name": "Info - Steam Ready",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "system emptying",
        "type": "system_emptying",
        "display_name": "Info - System Emptying",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "system filling",
        "type": "system_filling",
        "display_name": "Info - System Filling",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "ventilation closed",
        "type": "ventilation_closed",
        "display_name": "Alarm - Ventilation Closed",
        # "icon": "mdi:circle-outline",
        "device_class": "problem",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    {
        "name_pattern": "welcome",
        "type": "welcome",
        "display_name": "Info - Welcome",
        # "icon": "mdi:circle-outline",
        "device_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
]
